### ISSUE TITLE
Question about the reference point for HV

### ISSUE THREAD

**Issue by yeshenpy** [NYCU-RL-Bandits-Lab/Q-Pensieve#1]
Hello, how to determine the reference point in different tasks? Could you provide the details?

**Comment by yeshenpy** [comment]
In addition, I found that there is no universal function available for calculating the hypervolume (HV) indicator, and there is only a calculation interface for two-dimensional multi-objective optimization. Is it possible to provide a universal interface for HV calculation?

**Comment by yeshenpy** [comment]
How do you calculate the UT metric in PGMORL? PGMORL maintains a population of policies, and the policies can make decisions without relying on weights. So, how is UT calculated? Or, how do you assign corresponding weights to these policies in PGMORL?

**Comment by redway1225** [comment]
> Hello, how to determine the reference point in different tasks? Could you provide the details?

Regarding how to determine the reference point for different environments, our main approach is to evaluate the minimum value of each dimension of rewards in each environment. For example, although velocity in mujoco can have negative values, in most cases, we focus on positive values. In such situations, we set the reference point at 0. Another example is LunarLand, where the second dimension represents success with a score of 100 and failure with a score of -100. In this case, we set the reference point at -100.

**Comment by redway1225** [comment]
> In addition, I found that there is no universal function available for calculating the hypervolume (HV) indicator, and there is only a calculation interface for two-dimensional multi-objective optimization. Is it possible to provide a universal interface for HV calculation?

I apologize for the oversight. I have just added the calculation code for HV and UT based on Simon Wessing's code from 2010.

**Comment by redway1225** [comment]
> How do you calculate the UT metric in PGMORL? PGMORL maintains a population of policies, and the policies can make decisions without relying on weights. So, how is UT calculated? Or, how do you assign corresponding weights to these policies in PGMORL?

Regarding the comparison of PGMORL, we were unable to find a corresponding weight-based task to assist us in the calculations. Instead, we have established a pool to access the tasks during the training process. Each task has a corresponding preference, and the pool follows a first-in, first-out (FIFO) approach. The size of the pool is ten times the number of tasks. Each time, we search for the task with the minimum L2 norm of the preference we want to test and perform the calculations accordingly. With this approach, we attempt to provide a relatively fair calculation method.

**Comment by yeshenpy** [comment]
> Regarding the comparison of PGMORL, we were unable to find a corresponding weight-based task to assist us in the calculations. Instead, we have established a pool to access the tasks during the training process. Each task has a corresponding preference, and the pool follows a first-in, first-out (FIFO) approach. The size of the pool is ten times the number of tasks. Each time, we search for the task with the minimum L2 norm of the preference we want to test and perform the calculations accordingly. With this approach, we attempt to provide a relatively fair calculation method.

Thanks for your reply, Is the code available for the UT metric?

**Comment by yeshenpy** [comment]
> Regarding the comparison of PGMORL, we were unable to find a corresponding weight-based task to assist us in the calculations. Instead, we have established a pool to access the tasks during the training process. Each task has a corresponding preference, and the pool follows a first-in, first-out (FIFO) approach. The size of the pool is ten times the number of tasks. Each time, we search for the task with the minimum L2 norm of the preference we want to test and perform the calculations accordingly. With this approach, we attempt to provide a relatively fair calculation method.

I have an idea regarding the UT evaluation for PGMORL. Instead of evaluating only the tasks, we can directly evaluate all policies in the population. We can then select the maximum value based on our preference (for example, calculate for 19 preferences in 2 dim optimization problem) and calculate the UT by taking the average of these maximum values. Is this approach more reasonable?

**Comment by yeshenpy** [comment]
> Regarding how to determine the reference point for different environments, our main approach is to evaluate the minimum value of each dimension of rewards in each environment. For example, although velocity in mujoco can have negative values, in most cases, we focus on positive values. In such situations, we set the reference point at 0. Another example is LunarLand, where the second dimension represents success with a score of 100 and failure with a score of -100. In this case, we set the reference point at -100.

Since I want to reproduce the results of this paper, could you provide the minimum values for each task? This would help to avoid inconsistencies and ensure that the results are consistent.

**Comment by yeshenpy** [comment]
I have another question.
If we can only see the results at the end of the training, it means we cannot monitor the training process in real time. It seems like running the code once for a complete training cycle would take more than two days. Therefore, we are unable to make timely adjustments to the run. Is there any other way to monitor the training process in real time?

**Comment by yeshenpy** [comment]
When I run PGMORL, I noticed that the two papers used different environment settings. Apart from the different reward scales for different objectives mentioned in the papers, it seems that the maximum step size is also different. The paper uses a step size of 1000, while PGMORL uses 500. Why not use the settings of PGMORL? Besides, I have found that directly replacing the environment proposed in the paper with PGMORL does not work properly. Could you provide the complete code for training PGMORL?

**Comment by yeshenpy** [comment]
Furthermore, I have noticed that in PGMORL, even when a task is finished, it continues to execute and the results are recorded using a mask. Is it fair to not handle the problem? [https://github.com/mit-gfx/PGMORL/blob/71fd9ac1128ca129de4a7c8725d5f650e329379f/morl/mopg.py#L124](https://github.com/mit-gfx/PGMORL/blob/71fd9ac1128ca129de4a7c8725d5f650e329379f/morl/mopg.py#L124)
